config = {}

config.autopair = require('plugins.config.autopair')
config.bufferline = require('plugins.config.bufferline')
config.cmp = require('plugins.config.cmp')
config.comment = require('plugins.config.comment')
config.dap = require('plugins.config.dap')
config.hop = require('plugins.config.hop')
config.indent = require('plugins.config.indent')
config.lsp = require('plugins.config.lsp')
config.lspsaga = require('plugins.config.lspsaga')
config.lualine = require('plugins.config.lualine')
config.marks = require('plugins.config.marks')
config.neodev = require('plugins.config.neodev')
config.neorg = require('plugins.config.neorg')
config.hologram = require('plugins.config.hologram')
config.nullls = require('plugins.config.nullls')
config.outline = require('plugins.config.outline')
config.signature = require('plugins.config.signature')
config.surround = require('plugins.config.surround')
config.tabout = require('plugins.config.tabout')
config.telescope = require('plugins.config.telescope')
config.theme = require('plugins.config.theme')
config.todo = require('plugins.config.todo')
config.toggleterm = require('plugins.config.toggleterm')
config.filetree = require('plugins.config.filetree')
config.treesitter = require('plugins.config.treesitter')
config.notify = require('plugins.config.notify')
config.imguploader = require('plugins.config.imguploader')


return config
