# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export WORKSPACE=$HOME/.local/workspace
#
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:/opt:/usr/bin:$PATH:$GOPATH/bin:$GOROOT/bin:/usr/lib
export GOPATH=$HOME/Projects/go
export GOPROXY=https://goproxy.cn
export GO111MODULE=on
export XDG_CONFIG_HOME=$HOME/.config
# export https_proxy=http://127.0.0.1:7890
# export http_proxy=http://127.0.0.1:7890
export ALL_PROXY="socks5://127.0.0.1:7891"
export no_proxy='*.tuna.*'

# export LD_PRELOAD=/usr/lib/libproxychains.so.4

# For jetbrains
export IDEA_JDK=/usr/lib/jvm/jre-jetbrains
export STUDIO_JDK=/usr/lib/jvm/jre-jetbrains

export FZF_DEFAULT_OPTS="--height 80% --layout=reverse --border --preview '~/Documents/Other/fzf-scope.sh {} '"
export FZF_DEFAULT_COMMAND="fd --exclude={.wine,.git,.idea,.vscode,.sass-cache,node_modules,build,.local,.steam,.m2,.rangerdir,.ssh,.ghidra,.mozilla} --type f --hidden --follow"

vim_fzf() {
    local fzf_result=$(fzf)
    echo $fzf_result
    if [ -z "$fzf_result" ]
    then
        echo "No file specific, Interupt tne vim command"
    else
        nvim  $fzf_result
    fi
}

export LC_ALL="en_US.UTF-8"
export SAL_DISABLEGL=1
export NVM_NODEJS_ORG_MIRROR=http://npm.taobao.org/mirrors/node
# export _JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
alias android-studio="QT_QPA_PLATFORM=xcb _JAVA_AWT_WM_NONREPARENTING=1 android-studio"
alias mountusb="mkdir -p /home/ch4ser/Downloads/ShareFolder/usb;sudo mount /dev/sd* /home/ch4ser/Downloads/ShareFolder/usb"
alias umountusb="sudo umount /home/ch4ser/Downloads/ShareFolder/usb"
alias windows="VBoxManage startvm 'windows_the_one'"
alias kali="docker start kali ; docker attach kali"
alias ubuntu="docker start ubuntu ; docker attach ubuntu"
alias rasp="ssh root@192.168.31.75"
alias save_mode="sudo ryzenadj --stapm-limit=20000 --fast-limit=45000 --slow-limit=20000 --tctl-temp=60"
alias burst_mode="sudo ryzenadj --stapm-limit=45000 --fast-limit=45000 --slow-limit=45000 --tctl-temp=70"
alias volatility="vol"
alias msf="msfconsole"
alias clear_cache="yay -Scc;yay -Rns $(yay -Qtdq)"
alias clear_packages="yay -Qtdq | yay -Rs -"
alias idea="nohup /opt/intellij-idea-ultimate-edition/bin/idea.sh .  >/dev/null 2>&1 &"
alias check_log="journalctl -p5"
alias vim="nvim"
alias cdda="cataclysm"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias nvmstart="source /usr/share/nvm/init-nvm.sh"
alias java7="/usr/lib/jvm/java-7-openjdk/bin/java"
alias javac7="/usr/lib/jvm/java-7-openjdk/bin/javac"
alias java8="/usr/lib/jvm/java-8-openjdk/bin/java"
alias javac8="/usr/lib/jvm/java-8-openjdk/bin/javac"
alias py="python"
alias py2="python2"
alias ipy="ipython"
alias ipy2="ipython2"
alias pipi="pipenv shell"
alias server="ssh root@39.105.176.37"
alias tencent="ssh root@120.53.236.211"
alias vmwareon="sudo systemctl start vmware vmware-usbarbitrator vmware-networks-server vmware-workstation-server"

alias weather="curl -m 1 wttr.in\?format=3 2>/dev/null"
export ZSH="/usr/share/oh-my-zsh"
export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim


ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=9,bold'

plugins=(git)

source $ZSH/oh-my-zsh.sh

bindkey -e
bindkey -s '\er' 'ranger\n'
bindkey -s '\ev' 'vim_fzf\n'
bindkey -s '\ed' 'dolphin .\n'
bindkey -s '\ew' 'windows\n'

# for tomcat debug
# export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
# export JRE_HOME=$JAVA_HOME/jre
# export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
# export CATALINA_HOME=/usr/share/tomcat8
# export CLASSPATH=$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib:$CATALINA_HOME/lib
# export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$CATALINA_HOME/bin

# source /usr/share/nvm/init-nvm.sh
source /usr/share/autojump/autojump.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh 
source /usr/share/zsh/plugins/zsh-extract/extract.plugin.zsh
source /usr/share/nvm/init-nvm.sh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
source /opt/miniconda/etc/profile.d/conda.sh


# lf config
LFCD="/home/ch4ser/.config/lf/lfcd.sh"                                #  pre-built binary, make sure to use absolute path
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi
