# zmodload zsh/zprof
# wayland variables
# source $XDG_CONFIG_HOME/zsh/wayland


export WORKSPACE=$HOME/.local/workspace
#
export gw="http://120.53.236.211:8081"
export CGO_ENABLED=1
export GOPATH=$HOME/Projects/go
export GOPROXY=https://goproxy.cn
export GO111MODULE=on
export XDG_CONFIG_HOME=$HOME/.config
# export https_proxy=http://127.0.0.1:7890
# export http_proxy=http://127.0.0.1:7890
# export ALL_PROXY="socks5://127.0.0.1:7891"
# export no_proxy='*.tuna.*'
export PATH=$HOME/bin:/usr/local/bin:/opt:/usr/bin:$PATH:$GOPATH/bin:$GOROOT/bin:/usr/lib:$GOPATH/bin
# export LD_PRELOAD=/usr/lib/libproxychains.so.4

# For jetbrains
# export IDEA_JDK=/usr/lib/jvm/jre-jetbrains
# export STUDIO_JDK=/usr/lib/jvm/jre-jetbrains

export FZF_DEFAULT_OPTS="--height 80% --layout=reverse --border --preview 'bat --style=numbers --color=always --line-range :500 {}'"
export FZF_DEFAULT_COMMAND="fd --exclude={.wine,.git,.idea,.vscode,.sass-cache,node_modules,build,.local,.steam,.m2,.rangerdir,.ssh,.ghidra,.mozilla} --type f --hidden --follow"

xdg_fzf() {
    local fzf_result=$(fzf)
    echo $fzf_result
    if [ -z "$fzf_result" ]
    then
        echo "No file specific"
    else
        xdg-open $fzf_result &
    fi
}


export LC_ALL="en_US.UTF-8"
export NVM_NODEJS_ORG_MIRROR=http://npm.taobao.org/mirrors/node
# export _JAVA_OPTIONS='-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

export EDITOR=/usr/bin/nvim
export VISUAL=/usr/bin/nvim


plugins=(git)
# ZSH_THEME="funky"
source /usr/share/oh-my-zsh/oh-my-zsh.sh

bindkey -e
bindkey -s '\er' 'ranger\n'
bindkey -s '\ef' 'xdg_fzf\n'
bindkey -s '\ed' 'dolphin .\n'
bindkey -s '\ew' 'windows\n'

# for tomcat debug
# export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
# export JRE_HOME=$JAVA_HOME/jre
# export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
# export CATALINA_HOME=/usr/share/tomcat8530/apache-tomcat-8.5.30
export CLASSPATH=$HOME:$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib:$CATALINA_HOME/lib
export TODO_DIR=~/.local/share/todo
export TODO_ACTIONS_DIR=$XDG_CONFIG_HOME/todo/actions
export TODOTXT_DEFAULT_ACTION=ls
export TODOTXT_CFG_FILE=$XDG_CONFIG_HOME/todo/todo.cfg
export TODO_FILE=/home/ch4ser/.local/share/todo/todo.txt
# export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$CATALINA_HOME/bin

# for weblogic 
# export JAVA_HOME=/home/ch4ser/Tools/Environment/JDK/jdk1.8.0_112
# export JRE_HOME=$JAVA_HOME/jre
# export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin
# export CLASSPATH=$JAVA_HOME/jre/lib/rt.jar:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib:$CATALINA_HOME/lib
# export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin:$CATALINA_HOME/bin

# source /usr/share/nvm/init-nvm.sh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=9,bold,white,underline'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-extract/extract.plugin.zsh
source /usr/share/zsh/plugins/zsh-autoswitch-virtualenv/zsh-autoswitch-virtualenv.plugin.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme


alias vcam="~/Tools/Other/virtualcam.sh"
alias suspend="sudo systemctl suspend"
alias save_mode="cpupower-gui profile earth"
alias normal_mode="cpupower-gui config"
alias burst_mode="cpupower-gui profile Performance"
alias msf="msfconsole"
alias clear_cache="yay -Scc;yay -Rns $(yay -Qtdq)"
alias clear_packages="yay -Qtdq | yay -Rs -"
alias idea="nohup /opt/intellij-idea-ultimate-edition/bin/idea.sh .  >/dev/null 2>&1 &"
alias check_log="journalctl -p5"
alias vim="nvim"
alias neo="neovide"
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias nvmstart="source /usr/share/nvm/init-nvm.sh"
alias java7="/usr/lib/jvm/java-7-openjdk/bin/java"
alias javac7="/usr/lib/jvm/java-7-openjdk/bin/javac"
alias java8="/usr/lib/jvm/java-8-openjdk/bin/java"
alias javac8="/usr/lib/jvm/java-8-openjdk/bin/javac"
alias oracle8="/home/ch4ser/Tools/Environment/JDK/jdk1.8.0_112/bin/java"
alias php="php7"
alias py="python"
alias ipy="ipython"
alias server="ssh root@39.105.176.37"
alias tencent="ssh root@120.53.236.211"
alias thinkpad="ssh root@120.53.236.211 -p 45678"
alias ubuntu="ssh root@192.168.59.106"
alias ubuntu18="ssh root@192.168.59.110"
alias kali="ssh root@192.168.59.107"
alias centos="ssh root@192.168.59.108"
alias honeypot="ssh root@180.97.215.74"
alias k="kubectl"
alias faas="faas-cli"
alias cat="bat --style=plain --paging=never"
alias top="btm"
alias ls="exa --icons"
alias t="todo.sh"
alias cp="rsync -a"
alias start_clash="sudo systemctl start clash@root.service"
alias stop_clash="sudo systemctl stop clash@root.service"
eval "$(zoxide init zsh --cmd cd)"
alias docker_rm_all="docker ps -aq | xargs docker stop | xargs docker rm"
alias rslsync="rslsync --config ~/.config/rslsync/rslsync.conf"
alias mach_on='swaymsg input "1:1:AT_Translated_Set_2_keyboard" events toggle'

todo.sh list
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zstyle ':completion:*:default' list-colors '=(#b)(-*)(-- *)===34' '=(#b)(-- *)=34'

# zprof
